### ISSUE TITLE
编译安装后无网络

### ISSUE THREAD

**Issue by LunacyZeus** [cuu/ovpn_webview#1]
感觉是路由错了,但是使用同样的线路,openvpn connect可以连接,这个不能连接

**Comment by cuu** [comment]
没有,其实是这个用的不是直接的.ovpn文件,而是压缩过的一个格式,我没有放上来

**Comment by LunacyZeus** [comment]
是不是这个提供的哦~~
https://github.com/yangguangtongxun/FlowStorm

**Comment by cuu** [comment]
看着像...哥们你是要搞免流呢?

**Comment by LunacyZeus** [comment]
以前搞....现在不搞了~~~这个都和谐大半了.......我现在拿Openvpn来组网.2333333

**Comment by cuu** [comment]
真没想到,能遇上同行
黑产的大哥啊你是
回头有兴趣的加微信 _398437535_

这份代码我之前很早写了之后就一直扔着,早不管了,现在估计我自已看都头疼
因为我当时没打算把它写的很成熟,哈哈哈

**Comment by LunacyZeus** [comment]
哈哈,你这个代码还是要比流量卫士的要好点...那个我看到头疼~登录都不用json那种.

**Comment by liuxyon** [comment]
不要用微信了. 用xmpp
